name: Build Go binaries

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build
      uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.TOKEN }}
        goos: linux
        goarch: amd64
  trigger:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          TAG=${{ github.event.release.tag_name }}
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            https://api.github.com/repos/joekl17/mondoo-phase2/dispatches \
            -d '{"event_type":"trigger","client_payload":{"release_tag":"'"$TAG"'"}}'