name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  sast_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Semgrep SAST Scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: auto

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          
  release:
    runs-on: ubuntu-latest
    needs: [golangci, sast_scan]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.TOKEN }}